# Generated by Django 3.0.4 on 2020-03-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200322_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
