# Generated by Django 3.0.4 on 2020-03-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200322_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
    ]
